// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportBook.API.Data;

#nullable disable

namespace SportBook.API.Migrations
{
    [DbContext(typeof(SportBookContext))]
    partial class SportBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportBook.API.Models.BlokadaTermina", b =>
                {
                    b.Property<Guid>("IdBlokade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlokiraoKorisnik")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTerena")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("KrajBlokade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PocetakBlokade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Razlog")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBlokade");

                    b.HasIndex("BlokiraoKorisnik");

                    b.HasIndex("IdTerena");

                    b.ToTable("BlokadaTermina", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.Korisnik", b =>
                {
                    b.Property<Guid>("IdKorisnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JeAktivan")
                        .HasColumnType("bit");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKorisnika");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.KorisnikUloga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumDodjele")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdKorisnika")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUloge")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdKorisnika");

                    b.HasIndex("IdUloge");

                    b.ToTable("KorisnikUloga", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.Oprema", b =>
                {
                    b.Property<Guid>("IdOpreme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CijenaPosudbe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdObjekta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("JeAktivna")
                        .HasColumnType("bit");

                    b.Property<int>("KolicinaDostupna")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOpreme");

                    b.HasIndex("IdObjekta");

                    b.ToTable("Oprema", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.QRKod", b =>
                {
                    b.Property<Guid>("IdQrKoda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumGenerisanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdRezervacije")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("JeIskoristen")
                        .HasColumnType("bit");

                    b.Property<string>("KodVrijednost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQrKoda");

                    b.HasIndex("IdRezervacije")
                        .IsUnique();

                    b.ToTable("QRKod", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.RadnoVrijeme", b =>
                {
                    b.Property<Guid>("IdRadnogVremena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DanUSedmici")
                        .HasColumnType("smallint");

                    b.Property<Guid>("IdTerena")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("KrajRada")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("PocetakRada")
                        .HasColumnType("time");

                    b.Property<int>("TrajanjeTerminaMin")
                        .HasColumnType("int");

                    b.HasKey("IdRadnogVremena");

                    b.HasIndex("IdTerena");

                    b.ToTable("RadnoVrijeme", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.Recenzija", b =>
                {
                    b.Property<Guid>("IdRecenzije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdRezervacije")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("JeOdobrena")
                        .HasColumnType("bit");

                    b.Property<string>("Komentar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.HasKey("IdRecenzije");

                    b.HasIndex("IdRezervacije")
                        .IsUnique();

                    b.ToTable("Recenzija", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.Rezervacija", b =>
                {
                    b.Property<Guid>("IdRezervacije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumRezervacije")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdKorisnika")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTermina")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusPlacanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UkupnaCijena")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdRezervacije");

                    b.HasIndex("IdKorisnika");

                    b.HasIndex("IdTermina")
                        .IsUnique();

                    b.ToTable("Rezervacija", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.RezervacijaOprema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CijenaUkupno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdOpreme")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRezervacije")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOpreme");

                    b.HasIndex("IdRezervacije");

                    b.ToTable("RezervacijaOprema", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.Sport", b =>
                {
                    b.Property<Guid>("IdSporta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IkonaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSporta");

                    b.ToTable("Sport", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.SportskiObjekat", b =>
                {
                    b.Property<Guid>("IdObjekta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JeAktivan")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdObjekta");

                    b.ToTable("SportskiObjekat", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.Teren", b =>
                {
                    b.Property<Guid>("IdTerena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdObjekta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("JeAktivan")
                        .HasColumnType("bit");

                    b.Property<bool>("JeUnutarnji")
                        .HasColumnType("bit");

                    b.Property<int>("KapacitetIgraca")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlikaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipPodloge")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTerena");

                    b.HasIndex("IdObjekta");

                    b.ToTable("Teren", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.TerenSport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CijenaPоSatu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdSporta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTerena")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("JePrimarniSport")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdSporta");

                    b.HasIndex("IdTerena");

                    b.ToTable("TerenSport", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.Termin", b =>
                {
                    b.Property<Guid>("IdTermina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<Guid>("IdSporta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTerena")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Kraj")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("Pocetak")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTermina");

                    b.HasIndex("IdSporta");

                    b.HasIndex("IdTerena");

                    b.ToTable("Termin", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.Uloga", b =>
                {
                    b.Property<Guid>("IdUloge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUloge");

                    b.ToTable("Uloga", (string)null);
                });

            modelBuilder.Entity("SportBook.API.Models.BlokadaTermina", b =>
                {
                    b.HasOne("SportBook.API.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("BlokiraoKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportBook.API.Models.Teren", "Teren")
                        .WithMany()
                        .HasForeignKey("IdTerena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Teren");
                });

            modelBuilder.Entity("SportBook.API.Models.KorisnikUloga", b =>
                {
                    b.HasOne("SportBook.API.Models.Korisnik", "Korisnik")
                        .WithMany("KorisnikUloge")
                        .HasForeignKey("IdKorisnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportBook.API.Models.Uloga", "Uloga")
                        .WithMany()
                        .HasForeignKey("IdUloge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("SportBook.API.Models.Oprema", b =>
                {
                    b.HasOne("SportBook.API.Models.SportskiObjekat", "SportskiObjekat")
                        .WithMany("Oprema")
                        .HasForeignKey("IdObjekta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportskiObjekat");
                });

            modelBuilder.Entity("SportBook.API.Models.QRKod", b =>
                {
                    b.HasOne("SportBook.API.Models.Rezervacija", "Rezervacija")
                        .WithOne("QRKod")
                        .HasForeignKey("SportBook.API.Models.QRKod", "IdRezervacije")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SportBook.API.Models.RadnoVrijeme", b =>
                {
                    b.HasOne("SportBook.API.Models.Teren", "Teren")
                        .WithMany("RadnaVremena")
                        .HasForeignKey("IdTerena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teren");
                });

            modelBuilder.Entity("SportBook.API.Models.Recenzija", b =>
                {
                    b.HasOne("SportBook.API.Models.Rezervacija", "Rezervacija")
                        .WithOne("Recenzija")
                        .HasForeignKey("SportBook.API.Models.Recenzija", "IdRezervacije")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SportBook.API.Models.Rezervacija", b =>
                {
                    b.HasOne("SportBook.API.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IdKorisnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportBook.API.Models.Termin", "Termin")
                        .WithOne("Rezervacija")
                        .HasForeignKey("SportBook.API.Models.Rezervacija", "IdTermina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("SportBook.API.Models.RezervacijaOprema", b =>
                {
                    b.HasOne("SportBook.API.Models.Oprema", "Oprema")
                        .WithMany("RezervacijaOprema")
                        .HasForeignKey("IdOpreme")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportBook.API.Models.Rezervacija", "Rezervacija")
                        .WithMany("RezervacijaOprema")
                        .HasForeignKey("IdRezervacije")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oprema");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SportBook.API.Models.Teren", b =>
                {
                    b.HasOne("SportBook.API.Models.SportskiObjekat", "SportskiObjekat")
                        .WithMany("Tereni")
                        .HasForeignKey("IdObjekta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportskiObjekat");
                });

            modelBuilder.Entity("SportBook.API.Models.TerenSport", b =>
                {
                    b.HasOne("SportBook.API.Models.Sport", "Sport")
                        .WithMany("TerenSportovi")
                        .HasForeignKey("IdSporta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportBook.API.Models.Teren", "Teren")
                        .WithMany("TerenSportovi")
                        .HasForeignKey("IdTerena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");

                    b.Navigation("Teren");
                });

            modelBuilder.Entity("SportBook.API.Models.Termin", b =>
                {
                    b.HasOne("SportBook.API.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("IdSporta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportBook.API.Models.Teren", "Teren")
                        .WithMany("Termini")
                        .HasForeignKey("IdTerena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");

                    b.Navigation("Teren");
                });

            modelBuilder.Entity("SportBook.API.Models.Korisnik", b =>
                {
                    b.Navigation("KorisnikUloge");
                });

            modelBuilder.Entity("SportBook.API.Models.Oprema", b =>
                {
                    b.Navigation("RezervacijaOprema");
                });

            modelBuilder.Entity("SportBook.API.Models.Rezervacija", b =>
                {
                    b.Navigation("QRKod");

                    b.Navigation("Recenzija");

                    b.Navigation("RezervacijaOprema");
                });

            modelBuilder.Entity("SportBook.API.Models.Sport", b =>
                {
                    b.Navigation("TerenSportovi");
                });

            modelBuilder.Entity("SportBook.API.Models.SportskiObjekat", b =>
                {
                    b.Navigation("Oprema");

                    b.Navigation("Tereni");
                });

            modelBuilder.Entity("SportBook.API.Models.Teren", b =>
                {
                    b.Navigation("RadnaVremena");

                    b.Navigation("TerenSportovi");

                    b.Navigation("Termini");
                });

            modelBuilder.Entity("SportBook.API.Models.Termin", b =>
                {
                    b.Navigation("Rezervacija");
                });
#pragma warning restore 612, 618
        }
    }
}
